spring.application.name=devSns


# H2 Database (Server Mode)
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 Console (Optional, for development)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
#jwt.secret=7cb89b6399df27ebc401cb0286e60871a2d5bdd7445a0072065d3d5268ffd3cecf11f602961d6673f4c1ddb2295974f33dba3a8ab7168e2d5cb44924ae3b22a8
jwt.secret=${JWT_SECRET}